# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1ee34ce2ba082c021f3118572fafa2135aa9aaa633f73d43b56c331d4c5a24e9b9e5d8a7837b5dba021cc70c6909ea3e207b53e50caeecc8f6e478a6226a5a

test:
  secret_key_base: d49ed7b5bee9296d50b9edd935685a7c4b74986b3e7ff4735010b81889de0e12e7c03c2ce1ac5f8222d0054877fac5dc750714d1dc5c3e02ee7cdb45a5bd4e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
